### ISSUE TITLE
Error in install package

### ISSUE THREAD

**Issue by CCCBBG** [XSLiuLab/TCfinder#2]
It occured to following errors
devtools::install_github("XSLiuLab/TCfinder")

E  checking DESCRIPTION meta-information ...
   Malformed Authors@R field:
     <text>:3:55: unexpected ','
   2:     person("chenxu", "Wu", , "wuchx@shanghaitech.edu.cn", role = c("aut", "cre"),
   3:            comment = c(ORCID = "0009-0005-7257-4470")),
                                                            ^
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
Error: Failed to install 'TCfinder' from GitHub:
  ! System command 'R' failed

**Comment by qingjian1991** [comment]
I have the same error in package install

**Comment by wuchx101876** [comment]
> It occured to following errors devtools::install_github("XSLiuLab/TCfinder")
> 
> E checking DESCRIPTION meta-information ... Malformed Authors@R field: :3:55: unexpected ',' 2: person("chenxu", "Wu", , "[wuchx@shanghaitech.edu.cn](mailto:wuchx@shanghaitech.edu.cn)", role = c("aut", "cre"), 3: comment = c(ORCID = "0009-0005-7257-4470")), ^
> 
> See section 'The DESCRIPTION file' in the 'Writing R Extensions' manual. Error: Failed to install 'TCfinder' from GitHub: ! System command 'R' failed

The error has been resolved and you can reinstall

**Comment by wuchx101876** [comment]
> I have the same error in package install

The error has been resolved and you can reinstall

**Comment by CCCBBG** [comment]
> > 发生以下错误 devtools::install_github("XSLiuLab/TCfinder")
> > E 检查描述元信息...格式错误的 Authors@R 字段::3:55: 意外的 ',' 2: person("chenxu", "Wu", , " [wuchx@shanghaitech.edu.cn](mailto:wuchx@shanghaitech.edu.cn) ", role = c("aut", "cre"), 3: comment = c(ORCID = "0009-0005-7257-4470")),^
> > 请参阅“编写 R 扩展”手册中的“DESCRIPTION 文件”部分。错误：无法从 GitHub 安装“TCfinder”：！系统命令“R”失败
> 
> 错误已解决，您可以重新安装

thank you

**Comment by CCCBBG** [comment]
> > It occured to following errors devtools::install_github("XSLiuLab/TCfinder")
> > E checking DESCRIPTION meta-information ... Malformed Authors@R field: :3:55: unexpected ',' 2: person("chenxu", "Wu", , "[wuchx@shanghaitech.edu.cn](mailto:wuchx@shanghaitech.edu.cn)", role = c("aut", "cre"), 3: comment = c(ORCID = "0009-0005-7257-4470")), ^
> > See section 'The DESCRIPTION file' in the 'Writing R Extensions' manual. Error: Failed to install 'TCfinder' from GitHub: ! System command 'R' failed
> 
> The error has been resolved and you can reinstall

thank you
